### ISSUE TITLE
SAL can no longer return the currently available resources

### ISSUE THREAD

**Issue by atsag** [eu-nebulous/sal#12]
Assuming a registration of an AWS cloud resource has been successful from the part of the GUI, SAL is not able to return the node candidates which can be instantiated. Furthermore, SAL does not return the edge devices which are available to be used (so the list is empty)
This may also be related/attributed to an error on the side of the GUI - I am inclined though to think it is SAL which is the cause of the error as the GUI (sometimes) returns an API error indication inside a red box or in other occasions it returns a 500 error inside a red box, while also having no error logs (all this indicating that perhaps the backend does not return the appropriate data)

To reproduce, access to a gui user is needed, as well as to perform the process to register a cloud resource with AWS credentials.

**Comment by ankicabarisic** [comment]
To be sure it is SAL you should check on SAL logs, especially as there is no ProActive job to relate to :wink: otherwise we do not have any means to understand what happened: https://github.com/eu-nebulous/sal#report-issue
