### ISSUE TITLE
[SAL/PROACTIVE] Cluster deployment fails when worker node is of type c1.xlarge

### ISSUE THREAD

**Issue by jchmielewska** [eu-nebulous/sal#3]
Robert tried to deploy a cluster using POSTMAN on AWS. The master is a c5.xlarge instance, the worker is a c1.xlarge instance. The creation of master works OK. Worker node is instantiated (as seen on AWS panel) but the deployment task is stuck at 14% and the NodeSource on proactive shows the error "Description: Timeout occurred after 300000 ms.".

If master and worker are c5.xlarge, it works OK.

- This issue was reported by Robert and moved from Launchpad #2067514 [https://bugs.launchpad.net/nebulous/+bug/2067514](url)

@robert-sanfeliu asked:

> So, the question is: Does SAL/Proactive support c1.xlarge? If not, we can for sure blacklist them in the optimiser controller.

On the day 03.07 we tried to deploy Augmenta application and it happened again, master was deployed on c5 but the worker tried to deploy c1, and it was terminated.

**Comment by ankicabarisic** [comment]
@jchmielewska me and @robert-sanfeliu closed this yesterday?

**Comment by ankicabarisic** [comment]
it will be resolved by blacklisting the feature of optimizer/sal for unsupported instances...
