### ISSUE TITLE
Scape characters from env variables values

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/sal#5]
Characters `'` `"`  in environmental variables value should be escaped. If not, generated code for master/worker install script is incorrect and fails during execution.

Consider this request to define cluster:

```
.....
"env-var": {
        "AN_ENV_VARIABLE": "avalue",
    }
```

This will lead to the following script being generated and **successfully** executed:

```
# Environment variables preparation
echo "Exporting env vars ..."
source ./envVars.sh
echo "Done."

# Separation script

echo 'export AN_ENV_VARIABLE="avalue"' >> /home/ubuntu/.profile
source /home/ubuntu/.profile

```

Now consider this request to define cluster:

```
.....
"env-var": {
        "AN_ENV_VARIABLE": "av'alue",
    }
```
This will lead to the following script being generated:

```
# Environment variables preparation
echo "Exporting env vars ..."
source ./envVars.sh
echo "Done."

# Separation script

echo 'export AN_ENV_VARIABLE="av'alue"' >> /home/ubuntu/.profile
source /home/ubuntu/.profile

```

This script won't execute properly.

**Comment by ankicabarisic** [comment]
@robert-sanfeliu From SAL's perspective everything is OK, you can see that the variable command was generated equally. 

You are using the reserved Ubuntu terminal characters inside of your string, to be used in ubuntu correctly the following should be used:
'\''

However, best practice is to avoid these reserved characters. 
Why are you using this type of character to name env vars? Is it necessary?
If yes can optimizer handle them when sending request to SAL?

**Comment by robert-sanfeliu** [comment]
_Why are you using this type of character to name env vars? Is it necessary?_
Yes, we encountered it when trying to log in into docker registry where the password might contain this characters

_If yes can optimizer handle them when sending request to SAL?_
Can't SAL/Proactive handle it?

**Comment by ankicabarisic** [comment]
Hi, we can support this, but it was not intended that Unix operating system characters should appear in the env_vars. 
Therefore, I prefer to add this as an improvement task for 2nd iteration and in this case it makes sense to support all special unix characters which can cause problems like:

- Single Quote ('):
- Double Quote ("):
- Backslash (\):
- Dollar Sign ($):.
- Backtick (`):
- Ampersand (&):
- Asterisk (*):
- Question Mark (?):
- Square Brackets ([ and ]):
- Curly Braces ({ and }):
- Parentheses (( and )):
- Pipe (|):
- Greater Than (>):
- Less Than (<):
- Semicolon (;):
- Tilde (~):

**Comment by ankicabarisic** [comment]
@robert-sanfeliu any update regarding this request?

**Comment by ankicabarisic** [comment]
@robert-sanfeliu I will close this issue as there are no further updates
