### ISSUE TITLE
Question on "sessionid" header

### ISSUE THREAD

**Issue by npapageorgopoulos12** [eu-nebulous/sal#8]
## Clarification on Passing sessionid header

Hi team,

I'm working on some deployment testing using the Nebulous managed cluster, and I have a question regarding the pipeline of app creation configuration. Specifically, I'm trying to determine if there's a step where I need to pass the sessionid that I’m receiving from the pagateway/connect/ endpoint.

Thanks in advance for your help!

**Comment by ankicabarisic** [comment]
Hello, yes, the sessionId is used as a header for all the endpoints except the one to connect. 
You can have a look at this SAL usage section to understand how to form the calls: https://github.com/ow2-proactive/scheduling-abstraction-layer?tab=readme-ov-file#31-using-sal-rest-endpoints

**Comment by ankicabarisic** [comment]
@npapageorgopoulos12 Can you confirm that you manage to use sal now and if it is ok to close this issue?
